### ISSUE TITLE
[not urgent!] Fix project-board github action

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-common#10]
Not urgent, but the GH action fails both here and on fractal-web, with a ["Error: Input required and not supplied: github-token" message](https://github.com/fractal-analytics-platform/fractal-web/actions/runs/4290649640/jobs/7474882771). I think something should be configured in the repo settings, right? @jluethi

**Comment by jluethi** [comment]
@tcompa Ah, a token was missing. Added it now. Thanks for tagging me @tcompa
