### ISSUE TITLE
Introduce `docs_info` and `docs_link`

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-common#90]
Required for:
* https://github.com/fractal-analytics-platform/fractal-server/issues/549
* https://github.com/fractal-analytics-platform/fractal/issues/531

- [x] Add these two (`Optional[str]`) new fields to `TaskRead`, `TaskUpdate` and `TaskCreate`. In principle this can be done once, by adding them to `_TaskBase`, but I'm sometimes hesitant to rely too much on this inheritance pattern - which I don't always find transparent/readable. I'm fine with both choices.
- [x] Add these two new fields to `_TaskManifestBase`
- [x] Add tests? Probably not needed

**Comment by mfranzon** [comment]
> Add these two (Optional[str]) new fields to TaskRead, TaskUpdate and TaskCreate. In principle this can be done once, by adding them to _TaskBase, but I'm sometimes hesitant to rely too much on this inheritance pattern - which I don't always find transparent/readable. I'm fine with both choices.

Adding them to `_TaskBase` makes sense if we want to have them also on Import/Export models. As long as we want just the `source` field for these two models, let's update just `Task{Create,Read,Update}` 

> Add tests? Probably not needed

I think we can test just on the server
